### PR TITLE
Latest/v9

### LINKED ISSUE #83: Support for Ivy
While trying out the new Ivy engine, when trying to compile I got the following:

`ERROR in There is no format with import statements in '{PATH}/node_modules/ng-gapi' entry-point.`

### PR DESCRIPTION
**Pull request by rubenCodeforges**
Upgrade to Angular 9+

should fix #83

### CODE REVIEW

**Comment by jgololicic** [comment]
Hi Ruben, 

First of all thank you for upgrading the library!

I pulled the branch, built the lib locally and included it into my Angular 9 project. It works now. 
There is one thing to consider, please excuse me if I'm wrong. I got the following warning when running "ng serve":

```
Warning: Entry point 'ng-gapi' contains deep imports into '/path-to-my-project/node_modules/rxjs/Observable'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling ng-gapi : main as commonjs
```

I guess rx-compat dependency should be removed/replaced according to Angular upgrade todo docs (https://update.angular.io/#7.2:9.0l3):

> Once you and all of your dependencies have updated to RxJS 6, remove rxjs-compat.

**Comment by rubenCodeforges** [comment]
@jgololicic Hey , thanks for testing the pr !
Re the compat , probably its time to remove it

**Comment by Psycholive** [comment]
Hi guys! Thanks for your hard work. Maybe the rx-compat dependency problem could be tracked in a separate issue as we are very eager to see the fix for #83 released.

**Comment by runette** [comment]
Hi

I just started an Ivy based project that really needs this library.

It would be great if you could release this fix.

Thanks

**Pull request merged**
